### ISSUE TITLE
Attribute "use original class weapon animations" has an issue with switching weapons too quickly will hide your viewmodel

### ISSUE THREAD

**Issue by Whurrhurr** [rafradek/sigsegv-mvm#26]
https://github.com/rafradek/sigsegv-mvm/assets/33162051/c7781c67-8793-40f3-9e71-3a2c155815e5

switching away to a weapon without the attribute within a what feels like 0.1s interval will hide your viewmodel.

**Comment by rafradek** [comment]
It should be fixed now

**Comment by Whurrhurr** [comment]
> It should be fixed now

it still happens


https://github.com/rafradek/sigsegv-mvm/assets/33162051/8119c7d2-4a4e-475f-8213-7c6fb3622223
