### ISSUE TITLE
Invisible robots bug is back

### ISSUE THREAD

**Issue by Whurrhurr** [rafradek/sigsegv-mvm#29]
![image](https://github.com/rafradek/sigsegv-mvm/assets/33162051/5ce8b180-e51e-49da-93be-766e3ce3f4c9)
![invisible samurai demo](https://github.com/rafradek/sigsegv-mvm/assets/33162051/7d6f605d-bfa3-458b-8175-81cd676b78ae)
![invisible gmed](https://github.com/rafradek/sigsegv-mvm/assets/33162051/25c32959-73a8-42d9-bf03-3937642b5ab5)
![invisible gauntlet pusher](https://github.com/rafradek/sigsegv-mvm/assets/33162051/6ef4d8ce-3e77-4cf2-a3c8-760a87093dc0)

this ancient bug from the digital directive days has returned, some bots will show up with an invisible playermodel.

**Comment by rafradek** [comment]
Hope this is now fixed

**Comment by Whurrhurr** [comment]
still happens, seems to be tied to any active bot using a playermodel override with rafmod and failing the wave, watched a team fail Waters of a Robot Regime on Wave 4 with a boss bot with a custom model override, and after that, one bot was always invisible afterwards. then they failed the final wave, and another bot had an invisible playermodel
